sudo: required
services:
  - docker

before_install:
  - docker build -t brutebeer/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true brutebeer/react-test npm test -- --coverage

after_success:
  - docker build -t brutebeer/multi-client ./client
  - docker build -t brutebeer/muti-nginx ./nginx
  - docker build -t brutebeer/multi-server ./server
  - docker build -t brutebeer/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push brutebeer/multi-client
  - docker push brutebeer/muti-nginx
  - docker push brutebeer/multi-server
  - docker push brutebeer/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-491264435568
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
